"""add_enterprise_tables

Revision ID: c784b459e1d4
Revises: 
Create Date: 2026-03-04 12:06:06.574431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c784b459e1d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lan_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_lan_id'), 'users', ['lan_id'], unique=True)
    op.create_table('managers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_managers_team_id'), 'managers', ['team_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memberships_one_active_per_user', 'memberships', ['user_id'], unique=True, postgresql_where=sa.text('active = true'))
    op.create_index(op.f('ix_memberships_team_id'), 'memberships', ['team_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('team_change_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_change_requests_user_id'), 'team_change_requests', ['user_id'], unique=False)
    op.create_table('tracker_device_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rotated_from_id'], ['tracker_device_tokens.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_device_tokens_token_hash'), 'tracker_device_tokens', ['token_hash'], unique=False)
    op.add_column('audit_log', sa.Column('actor_user_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('actor_team_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('target_team_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('request_id', sa.String(length=64), nullable=True))
    op.add_column('audit_log', sa.Column('extra_data', sa.Text(), nullable=True))
    op.create_index(op.f('ix_audit_log_request_id'), 'audit_log', ['request_id'], unique=False)
    op.create_foreign_key(None, 'audit_log', 'teams', ['actor_team_id'], ['id'])
    op.create_foreign_key(None, 'audit_log', 'teams', ['target_team_id'], ['id'])
    op.create_foreign_key(None, 'audit_log', 'users', ['actor_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_request_id'), table_name='audit_log')
    op.drop_column('audit_log', 'extra_data')
    op.drop_column('audit_log', 'request_id')
    op.drop_column('audit_log', 'target_team_id')
    op.drop_column('audit_log', 'actor_team_id')
    op.drop_column('audit_log', 'actor_user_id')
    op.drop_index(op.f('ix_tracker_device_tokens_token_hash'), table_name='tracker_device_tokens')
    op.drop_table('tracker_device_tokens')
    op.drop_index(op.f('ix_team_change_requests_user_id'), table_name='team_change_requests')
    op.drop_table('team_change_requests')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_team_id'), table_name='memberships')
    op.drop_index('ix_memberships_one_active_per_user', table_name='memberships', postgresql_where=sa.text('active = true'))
    op.drop_table('memberships')
    op.drop_index(op.f('ix_managers_team_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_users_lan_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
